// The consumer-facing virtual module declarations (config, hooks, stores) live
// in `virtual-modules.d.ts` so they can be both injected into consuming apps via
// `injectTypes` and picked up here for internal typechecking by tsconfig's
// `include` glob.

declare module "*.astro" {
  const Component: import("astro/runtime/server/index.js").AstroComponentFactory;
  export default Component;
}

// Minimal `any`-typed version of the `astro:db` virtual module. In reality,
// types are generated by `astro sync` in the consuming app, but @astrojs/db may
// not be installed here as it's an optional peer dep.
declare module "astro:db" {
  export const db: any;
  export function eq(column: any, value: any): any;
  export function defineDb(config: any): any;
  export function defineTable(config: any): any;
  export const column: {
    text(): any;
    number(): any;
    boolean(): any;
    date(): any;
    json(): any;
  };
}
